/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/robot_t.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/robot_t.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="ExoSkeleton">
          <primitive object={nodes.CTRL_FK_PelvisBase001} />
          <primitive object={nodes.CTRL_IK_Neck001} />
          <primitive object={nodes.CTRL_IK_ArmL002} />
          <primitive object={nodes.POLE_IK_ArmL002} />
          <primitive object={nodes.CTRL_IK_LegJointL003} />
          <primitive object={nodes.CTRL_IK_LegJointR003} />
          <primitive object={nodes.POLE_IK_LegJointR001} />
          <primitive object={nodes.POLE_IK_LegJointL002} />
          <primitive object={nodes.DEF_PelvisBase001} />
          <primitive object={nodes.DEF_LegJointL001} />
          <primitive object={nodes.DEF_LegJointR001} />
          <primitive object={nodes.MCH_FK_LegJointL001} />
          <primitive object={nodes.MCH_FK_LegJointR001} />
          <primitive object={nodes.POLE_IK_PelvisBase001} />
          <primitive object={nodes.MCH_IK_LegJointL001} />
          <primitive object={nodes.MCH_IK_LegJointR001} />
          <skinnedMesh name="ArmJoint_L" geometry={nodes.ArmJoint_L.geometry} material={materials.Metal_02} skeleton={nodes.ArmJoint_L.skeleton} />
          <skinnedMesh name="ArmJoint_R" geometry={nodes.ArmJoint_R.geometry} material={materials.Metal_02} skeleton={nodes.ArmJoint_R.skeleton} />
          <skinnedMesh name="BellyJoint" geometry={nodes.BellyJoint.geometry} material={materials.Metal_02} skeleton={nodes.BellyJoint.skeleton} />
          <skinnedMesh name="ChestPiece001" geometry={nodes.ChestPiece001.geometry} material={materials.Metal_01} skeleton={nodes.ChestPiece001.skeleton} />
          <skinnedMesh name="ChestPiece002" geometry={nodes.ChestPiece002.geometry} material={materials.Metal_02} skeleton={nodes.ChestPiece002.skeleton} />
          <skinnedMesh name="ChestPiece003" geometry={nodes.ChestPiece003.geometry} material={materials.Metal_01} skeleton={nodes.ChestPiece003.skeleton} />
          <skinnedMesh name="ChestPiece004" geometry={nodes.ChestPiece004.geometry} material={materials.Metal_02} skeleton={nodes.ChestPiece004.skeleton} />
          <skinnedMesh name="DumbHead39002" geometry={nodes.DumbHead39002.geometry} material={materials.MetalHeart} skeleton={nodes.DumbHead39002.skeleton} />
          <skinnedMesh name="Foot_L" geometry={nodes.Foot_L.geometry} material={materials.Metal_02} skeleton={nodes.Foot_L.skeleton} />
          <skinnedMesh name="Foot_R" geometry={nodes.Foot_R.geometry} material={materials.Metal_02} skeleton={nodes.Foot_R.skeleton} />
          <skinnedMesh name="ForeArm_L" geometry={nodes.ForeArm_L.geometry} material={materials.Metal_01} skeleton={nodes.ForeArm_L.skeleton} />
          <skinnedMesh name="ForeArm_R" geometry={nodes.ForeArm_R.geometry} material={materials.Metal_01} skeleton={nodes.ForeArm_R.skeleton} />
          <skinnedMesh name="Hands_L" geometry={nodes.Hands_L.geometry} material={materials.Guns} skeleton={nodes.Hands_L.skeleton} />
          <skinnedMesh name="Hands_R" geometry={nodes.Hands_R.geometry} material={materials.Guns} skeleton={nodes.Hands_R.skeleton} />
          <skinnedMesh name="HandSlice_L" geometry={nodes.HandSlice_L.geometry} material={materials.Metal_02} skeleton={nodes.HandSlice_L.skeleton} />
          <skinnedMesh name="HandSlice_R" geometry={nodes.HandSlice_R.geometry} material={materials.Metal_02} skeleton={nodes.HandSlice_R.skeleton} />
          <skinnedMesh name="Heart" geometry={nodes.Heart.geometry} material={materials.MetalHeart} skeleton={nodes.Heart.skeleton} />
          <skinnedMesh name="Leg_L" geometry={nodes.Leg_L.geometry} material={materials.Metal_02} skeleton={nodes.Leg_L.skeleton} />
          <skinnedMesh name="Leg_R" geometry={nodes.Leg_R.geometry} material={materials.Metal_02} skeleton={nodes.Leg_R.skeleton} />
          <skinnedMesh name="LegAdd_L" geometry={nodes.LegAdd_L.geometry} material={materials.Metal_01} skeleton={nodes.LegAdd_L.skeleton} />
          <skinnedMesh name="LegAdd_R" geometry={nodes.LegAdd_R.geometry} material={materials.Metal_01} skeleton={nodes.LegAdd_R.skeleton} />
          <skinnedMesh name="LegBottom_L" geometry={nodes.LegBottom_L.geometry} material={materials.Metal_01} skeleton={nodes.LegBottom_L.skeleton} />
          <skinnedMesh name="LegBottom_R" geometry={nodes.LegBottom_R.geometry} material={materials.Metal_01} skeleton={nodes.LegBottom_R.skeleton} />
          <skinnedMesh name="LegJoint_L" geometry={nodes.LegJoint_L.geometry} material={materials.Metal_01} skeleton={nodes.LegJoint_L.skeleton} />
          <skinnedMesh name="LegJoint_R" geometry={nodes.LegJoint_R.geometry} material={materials.Metal_01} skeleton={nodes.LegJoint_R.skeleton} />
          <skinnedMesh name="LegMuscle_L" geometry={nodes.LegMuscle_L.geometry} material={materials.Metal_02} skeleton={nodes.LegMuscle_L.skeleton} />
          <skinnedMesh name="LegMuscle_R" geometry={nodes.LegMuscle_R.geometry} material={materials.Metal_02} skeleton={nodes.LegMuscle_R.skeleton} />
          <skinnedMesh name="LegPiece_L" geometry={nodes.LegPiece_L.geometry} material={materials.Metal_02} skeleton={nodes.LegPiece_L.skeleton} />
          <skinnedMesh name="LegPiece_R" geometry={nodes.LegPiece_R.geometry} material={materials.Metal_02} skeleton={nodes.LegPiece_R.skeleton} />
          <skinnedMesh name="Pelvis" geometry={nodes.Pelvis.geometry} material={materials.Metal_02} skeleton={nodes.Pelvis.skeleton} />
          <skinnedMesh name="ShoulderJoint_L" geometry={nodes.ShoulderJoint_L.geometry} material={materials.Metal_01} skeleton={nodes.ShoulderJoint_L.skeleton} />
          <skinnedMesh name="ShoulderJoint_R" geometry={nodes.ShoulderJoint_R.geometry} material={materials.Metal_01} skeleton={nodes.ShoulderJoint_R.skeleton} />
          <skinnedMesh name="ShouldersRest_L" geometry={nodes.ShouldersRest_L.geometry} material={materials.MetalHeart} skeleton={nodes.ShouldersRest_L.skeleton} />
          <skinnedMesh name="ShouldersRest_R" geometry={nodes.ShouldersRest_R.geometry} material={materials.MetalHeart} skeleton={nodes.ShouldersRest_R.skeleton} />
          <skinnedMesh name="ShoulderTwist_L" geometry={nodes.ShoulderTwist_L.geometry} material={materials.Metal_02} skeleton={nodes.ShoulderTwist_L.skeleton} />
          <skinnedMesh name="ShoulderTwist_R" geometry={nodes.ShoulderTwist_R.geometry} material={materials.Metal_02} skeleton={nodes.ShoulderTwist_R.skeleton} />
          <skinnedMesh name="Belly_Bottom002" geometry={nodes.Belly_Bottom002.geometry} material={materials.Metal_01} skeleton={nodes.Belly_Bottom002.skeleton} />
          <skinnedMesh name="Belly_Bottom003" geometry={nodes.Belly_Bottom003.geometry} material={materials.Metal_02} skeleton={nodes.Belly_Bottom003.skeleton} />
          <skinnedMesh name="Belly_Bottom001" geometry={nodes.Belly_Bottom001.geometry} material={materials.Metal_02} skeleton={nodes.Belly_Bottom001.skeleton} />
          <skinnedMesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} skeleton={nodes.Sphere002.skeleton} />
          <skinnedMesh name="Thigh_L" geometry={nodes.Thigh_L.geometry} material={materials.Metal_01} skeleton={nodes.Thigh_L.skeleton} />
          <skinnedMesh name="Thigh_R" geometry={nodes.Thigh_R.geometry} material={materials.Metal_01} skeleton={nodes.Thigh_R.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/robot_t.glb')
