apiVersion: v1
kind: Service
metadata:
  name: app-main-service
  labels:
    app: img-1
spec:
  selector:
    app: img-1
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
