/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/cello_t.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cello_t(props : any) {
  const { nodes, materials } : any = useGLTF('/cello_t.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry} material={materials.DeepWood} position={[0, 2.44, 0]} />
      <mesh geometry={nodes.Leg.geometry} material={materials.Metal_Silver} position={[0, 0.02, 0]} />
      <mesh geometry={nodes.BridgeHolder.geometry} material={materials.BridgeHolder_Plastic_Black} position={[0.32, 0, 0]} />
      <mesh geometry={nodes.StringSustainer.geometry} material={materials.StringSustainer_NaturalWood} position={[0.04, 0, 0]} />
      <mesh geometry={nodes.Leg_Head.geometry} material={materials.Metal_Gold} position={[0, 0.24, 0]} />
      <mesh geometry={nodes.StringTuningScrews.geometry} material={materials.Metal_Silver} position={[0.41, 1.56, -0.05]} rotation={[0, 0, -1.91]} />
      <mesh geometry={nodes.StringHolders.geometry} material={materials.Metal_Silver} position={[0.41, 1.63, -0.06]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Leg_Tip.geometry} material={materials.Rubber_Black} position={[0, 0.05, 0]} />
      <mesh geometry={nodes.BottomGripPiece.geometry} material={materials.Wood_Black} position={[0, 2.41, 0]} />
      <mesh geometry={nodes.BridgeHolder_Support.geometry} material={materials.Metal_Black} position={[0.01, -0.02, 0]} />
      <mesh geometry={nodes.Knut.geometry} material={materials.Wood_Black} position={[0.4, -0.02, 0]} />
      <mesh geometry={nodes.NeckPiece.geometry} material={materials['DeepWoodTop.001']} position={[0.07, 4.05, 0]} rotation={[Math.PI / 2, -1.57, 0]}>
        <mesh geometry={nodes.NeckPiece001.geometry} material={materials.Wood_BridgeCover} />
      </mesh>
      <mesh geometry={nodes.KeyEdge_02.geometry} material={materials.Wood_Black} position={[-0.05, 4.29, -0.18]} rotation={[Math.PI, 0, 1.23]} />
      <mesh geometry={nodes.Key_Leg.geometry} material={materials.Metal_Silver} position={[0, 0.78, 0.06]} />
      <mesh geometry={nodes.StringTuningScrews_Grippers.geometry} material={materials.Metal_Silver} position={[0.37, 1.57, -0.05]} rotation={[0, 0, -1.91]} />
      <mesh geometry={nodes.Retopo_String_01.geometry} material={materials['String_Metal.001']} position={[0.54, 2.11, -0.03]} rotation={[0, 0, -1.38]}>
        <mesh geometry={nodes.Retopo_String_01001.geometry} material={materials['String_Purple.001']} />
      </mesh>
      <mesh geometry={nodes.Retopo_String_02.geometry} material={materials['String_Metal.002']} position={[0.54, 2.11, 0.01]} rotation={[0, 0, -1.38]}>
        <mesh geometry={nodes.Retopo_String_02001.geometry} material={materials['String_Teal.001']} />
      </mesh>
      <mesh geometry={nodes.Retopo_String_03.geometry} material={materials['String_Metal.003']} position={[0.54, 2.11, 0.05]} rotation={[0, 0, -1.38]}>
        <mesh geometry={nodes.Retopo_String_03001.geometry} material={materials['String_Green.001']} />
      </mesh>
      <mesh geometry={nodes.Retopo_String_04.geometry} material={materials['String_Metal.004']} position={[0.54, 2.11, 0.08]} rotation={[0, 0, -1.38]}>
        <mesh geometry={nodes.Retopo_String_04001.geometry} material={materials['String_Black.001']} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/cello_t.glb')
